[options]
; Master password para DB Manager
admin_passwd = 8jK!2pQv7mR#sT4x

; Conexión a Postgres (servicio "db" en docker compose)
db_host = db
db_port = 5432
db_user = odoo
db_password = centroManzan0

; Datos persistentes
data_dir = /var/lib/odoo

; Addons
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

; Permitir ver/gestionar múltiples bases
list_db = True

; NOTA: NO fijar db_name si quieres ver todas las DB
; db_name = cer_prod

; proxy_mode = True
